### ISSUE TITLE
conditional usage

### ISSUE THREAD

**Issue by jaybuddy** [Beskhue/CookieTokenAuth#19] opened 2017-11-17 21:33 UTC
Hello!

I am implementing your plugin conditionally as described in the "Disable automatic generation of token cookies" section of the readme.

My Auth Component load (in AppController) looks like this:
```
        $this->loadComponent('Auth', [
            'authenticate' => [
                'Beskhue/CookieTokenAuth.CookieToken' => [
                    'fields' => ['username' => 'email'],
                    'setCookieAfterIdentify' => false,
                    'minimizeCookieExposure' => true,
                ],
                'Form' => [
                    'fields' => ['username' => 'email'],
                ],
            ],
            'logoutRedirect' => [
                'controller' => 'Users',
                'action' => 'login'
            ],
            'unauthorizedRedirect' => [
                'controller' => 'Users',
                'action' => 'login'
            ]
        ]);
```

My Login method in UsersController contains the following:
```
            if( $this->request->getData('remember_me') ) {
                
                $this->loadComponent(
                    'Beskhue/CookieTokenAuth.CookieToken',
                    $this->Auth->getConfig('authenticate')['Beskhue/CookieTokenAuth.CookieToken']
                );
                $this->CookieToken->setCookie($user);
            }
```

When I login and don't check remember me, It creates a token and adds a record to the auth_tokens table despite ` 'setCookieAfterIdentify' => false,` Is this expected behavior?

When I login and do check remember me, I get the following error: 
```
The "CookieToken" alias has already been loaded with the following config: array ( 'fields' => array ( 'username' => 'email', 'password' => 'password', ), 'userModel' => 'Users', 'scope' => array ( ), 'finder' => 'all', 'contain' => NULL, 'passwordHasher' => 'Default', 'hash' => 'sha256', 'cookie' => array ( 'name' => 'userdata', 'expires' => '+10 weeks', ), 'minimizeCookieExposure' => true, 'setCookieAfterIdentify' => false, ) which differs from array ( 'fields' => array ( 'username' => 'email', ), 'setCookieAfterIdentify' => false, 'minimizeCookieExposure' => true, )
```

This leads me to believe the Beskhue/CookieTokenAuth.CookieToken component should not be loaded in the AppController if it is being loaded in the UserController conditionally. Is that correct?

Do you have any suggestions or things I should look at that may help resolve this for me?

**Comment by tomcur** [comment] 2017-11-18 22:28
Hey,

Probably something went wrong in this part when getting the configuration:

```php
$this->loadComponent(
    'Beskhue/CookieTokenAuth.CookieToken',
    $this->Auth->getConfig('authenticate')['Beskhue/CookieTokenAuth.CookieToken']
);
```

Most likely it does not correctly grab the entire configuration (with defaults filled in).

I have made some slight changes to better support this use-case and make it less prone to errors. You can now do:

```php
if($this->request->getData('remember_me')) {
    $cookieTokenComponent = $this->Auth->getAuthenticate('Beskhue/CookieTokenAuth.CookieToken')->getCookieTokenComponent();
    $cookieTokenComponent->setCookie($user['id']);
}
```

The master branch has been updated. I will make a new release, tomorrow evening by the latest.

I will see if I can reproduce the issue where a token is always created even though `setCookieAfterIdentify` is false.

**Comment by tomcur** [comment] 2017-11-18 22:29
Note that due to some other changes just merged on the master branch you now need to call `setCookie` with the user id, and not the user entity.

**Comment by tomcur** [comment] 2017-11-18 23:05
I just released version 2.0.0. This simplifies supporting conditional token cookie creation.

I have not been able to reproduce the issue where tokens are added to the database, even though `setCookieAfterIdentify` is `false`, and the "remember me"-button is not checked.

If that issue remains, please open a new issue so we can track it separately.

**Closed as completed by tomcur** 2017-11-18 23:05 UTC

**Comment by jaybuddy** [comment] 2017-11-19 16:53
Works like a charm! Thanks for the new release!

**Comment by tomcur** [comment] 2017-11-19 19:27
Great!
